services:
  # configserver:
  #   build: ./config-server
  #   ports:
  #     - '8082:8082'

  # apigateway:
  #   build: ./api-gateway
  #   ports:
  #     - '8090:8090'
  #   depends_on:
  #     - configserver

  eurekaserver:
    build: ./service-server
    ports:
      - '8761:8761'

  rekammedis:
    build: ./rekamMedis
    ports:
      - '8080:8080'
    depends_on:
      - eurekaserver
      

  # frontend:
  #   build: ./fe-rekammedis
  #   depends_on:
  #     - rekammedis
  #   ports:
  #     - '3000:3000'
