services:
  eurekaserver:
    build: ./service-server
    ports:
      - '8761:8761'

  rekammedis:
    build: ./rekamMedis
    ports:
      - '8080:8080'
    depends_on:
      - eurekaserver

  apigateway:
    build: ./api-gateway
    ports:
      - '8090:8090'
    depends_on:
      - eurekaserver

  frontend:
    build: ./fe-rekammedis
    depends_on:
      - rekammedis
    ports:
      - '3000:3000'

  nodeserver:
    build: ./node-server
    ports:
      - '3001:3001'
