services:
  rekammedis:
    build: ./rekamMedis
    ports:
      - '8080:8080'
    depends_on:
      - configserver
      - apigateway

  frontend:
    build: ./fe-rekammedis
    depends_on:
      - rekammedis

  apigateway:
    build: ./api-gateway
    ports:
      - '8090:8090'
    depends_on:
      - configserver

  configserver:
    build: ./config-server
    ports:
      - '8082:8082'
